# Generated by Django 3.2.5 on 2021-07-23 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_ku', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='no',
            field=models.IntegerField(default=None),
        ),
    ]
